name: CLI CI

on:
  pull_request:
    paths:
      - "cli/**"
      - ".github/workflows/ci-cli.yml"
  push:
    branches:
      - main
    paths:
      - "cli/**"
      - ".github/workflows/ci-cli.yml"
  workflow_call:

concurrency:
  group: ci-cli-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Rust CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        working-directory: cli
        run: cargo fmt --check

      - name: Run tests
        working-directory: cli
        run: cargo test -j 1
